### ISSUE TITLE
Making the model public?

### ISSUE THREAD

**Issue by ieee8023** [JianboJiao/AWCL#1]
Hello,

Do you have a time estimate when the code and model weights will be made public here?

-Joseph

**Comment by JianboJiao** [comment]
Hello Joseph,

Apologies for the delay.

Now the code has been released, please feel free to check it out and let me know if you have any questions.

Best,
Jianbo

**Comment by ieee8023** [comment]
Thanks! What is the license for the code and mode?

**Comment by JianboJiao** [comment]
It is the BSD-2-Clause license, thanks!
